# Generated by Django 4.1.4 on 2022-12-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userapp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinf', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=50)),
                ('nomi', models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue')], max_length=50)),
                ('fanlar', models.ManyToManyField(to='maktabapp.fanlar')),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField(max_length=50)),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.sinf')),
            ],
        ),
        migrations.CreateModel(
            name='Oqtuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familya', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.account')),
                ('fan', models.ManyToManyField(to='maktabapp.fanlar')),
            ],
        ),
        migrations.CreateModel(
            name='Chorak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=50)),
                ('baho1', models.PositiveIntegerField(blank=True, null=True)),
                ('baho2', models.PositiveIntegerField(blank=True, null=True)),
                ('baho3', models.PositiveIntegerField(blank=True, null=True)),
                ('baho4', models.PositiveIntegerField(blank=True, null=True)),
                ('oqtuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.oqtuvchi')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktabapp.oquvchi')),
            ],
        ),
    ]
